### ISSUE TITLE
ListDialogFragment OnClickListener API

### ISSUE THREAD

**Issue by marcoRS** [avast/android-styled-dialogs#100]
I'm having trouble figuring out how to set up a item click listener using a ListDialogFragment. From looking at the code I don't immediately see it. 

Is there plans to support a similar API like an AlertDialogBuilder? I'm referring to the following:

        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
          builder.setNegativeButton(android.R.string.cancel, null)
          .setItems(R.array.items, new OnClickListener() {
                 public void onClick(DialogInterface dialog, int which) {
                   // react to item selected. 
                }
        });

**Comment by destil** [comment]
Please have a look in the demo app. We can't use similar API to AlertDialog, because we use DialogFragments.
