### ISSUE TITLE
Smooth fading and uprising

### ISSUE THREAD

**Issue by georgeci** [avast/android-styled-dialogs#107]
On my 4.4 android dialogs appeared sharply

**Comment by destil** [comment]
Sorry, what's the problem? Can you be more specific?

**Comment by georgeci** [comment]
Reformulate the thought. How to add animation to the appearance and hide the dialog?

**Comment by destil** [comment]
The library doesn't support it. You could do it with custom dialogs. But it would be a nice addition to the library, would you like to add it and send a pull request?

**Comment by georgeci** [comment]
I can try. An interesting case for the weekend.

**Comment by georgeci** [comment]
I understand. Your theme inherited from the "android:Theme", it already has the necessary animation. I just got used to the style of Holo.
