### ISSUE TITLE
Dialogs width on Tablets

### ISSUE THREAD

**Issue by marta-rodriguez** [avast/android-styled-dialogs#110]
Using this library when I show a dialog on tablet its width always matches parent, but I don't want it always. When using simple dialogs I just want a small dialog.

**Comment by destil** [comment]
Can you attach a screenshot? Do native dialogs on Lollipop behave differently?

**Comment by marta-rodriguez** [comment]
It is a Samsung Galaxy Tab 4 with Android 4.4.2
![device-2015-03-16-134737](https://cloud.githubusercontent.com/assets/1157385/6666275/109883c0-cbe3-11e4-9fd8-e24c70183d94.png)

I don't have a lollipop tablet here, so I can't check it.

**Comment by marta-rodriguez** [comment]
Finally I have override the styles to fix the issue for tablets and it works fine also on mobile:

```
    <style name="SDL.Layout">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">match_parent</item>
        <item name="android:orientation">vertical</item>
    </style>

    <style name="SDL.ScrollView">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
    </style>

    <style name="SDL.TextView.Title">
        <item name="android:textSize">20sp</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:textColor">?sdlTextPrimaryColor</item>
        <!-- paddings set in code -->
    </style>

    <style name="SDL.Layout.Buttons">
        <item name="android:orientation">horizontal</item>
        <item name="android:layout_height">@dimen/grid_12</item>
        <item name="android:gravity">center_vertical</item>
        <item name="android:layout_gravity">right</item>
        <item name="android:paddingLeft">0dp</item>
        <item name="android:paddingRight">0dp</item>
    </style>

    <style name="SDL.Expander">
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_height">0dp</item>
    </style>
```

**Comment by destil** [comment]
I have checked native dialogs on Lollipop and they indeed have some smaller width on tablet's landscape orientation. We will fix that in the next version of the library or we will accept a pull request.

@marta-rodriguez Your solution is not correct, dialogs on Lollipop are not 'wrap_content' but they have some minimal width. The exact value must be found in Android source code.

**Comment by marta-rodriguez** [comment]
Yes, you are correct. I have been working on it again and the problem is with the "Expander" for the buttons, it makes the dialog always "match_parent" so it is too big for tablets. I'm trying to fix it.

**Comment by destil** [comment]
@marta-rodriguez When you fix it, please send a pull request. Maybe it would be good idea to ditch Expander and replace it with RelativeLayout positioning for buttons.

**Comment by marta-rodriguez** [comment]
I have sent you a pull request
