### ISSUE TITLE
Support for Light Dialogs in Dark Themed projects

### ISSUE THREAD

**Issue by major-laslo** [avast/android-styled-dialogs#113]
I might be missing something obvious in which case I apologize profusely, but is there a simple way to use light dialogs in a dark themed app now with v2.2.0?

There are projects which use dark theme as a base but light dialogs fit their visual identity better. In these cases there should be a way to force the library to keep using the light dialogs on a theme/project level.

Thanks!

**Comment by destil** [comment]
You are not missing something obvious. We added method useDarkTheme() but not useLightTheme(). We will accept a pull request.
