### ISSUE TITLE
Maximized dialog width if buttons setted

### ISSUE THREAD

**Issue by imShara** [avast/android-styled-dialogs#116]
Width not adjusted by content

**Comment by destil** [comment]
This issue is not clear, please add more description and screenshot

**Comment by imShara** [comment]
![android-l](https://cloud.githubusercontent.com/assets/4913196/7258360/b5e27064-e864-11e4-8094-2cbc1fb898b3.png)
android-l dialog in settings

![styled-dialogs](https://cloud.githubusercontent.com/assets/4913196/7258358/b5dd4eea-e864-11e4-8afd-45be20b98949.png)
[android-styled-dialogs](https://github.com/avast/android-styled-dialogs)

![materia-dialogs](https://cloud.githubusercontent.com/assets/4913196/7258359/b5e0b6ca-e864-11e4-8266-206ccd42c59f.png)
[material-dialogs](https://github.com/afollestad/material-dialogs)

**Comment by destil** [comment]
This was fixed by a PR some time ago, I will release a new version today.
