### ISSUE TITLE
can not perform this action after onsaveinstancestate

### ISSUE THREAD

**Issue by THEONE10211024** [avast/android-styled-dialogs#122]
I must say you did a really good job! And I'm quite interested in the problem: "can not perform this action after onsaveinstancestate".Did you meet the problem,and how you solved it.Thank you!

**Comment by Gongcong** [comment]
i have the same problem when i use loader,and dismiss dialog in onLoadFinished

**Comment by destil** [comment]
You need to check isAdded() in onLoaderFinished before you dismiss the dialog.
