### ISSUE TITLE
Add support for dialog icon 

### ISSUE THREAD

**Issue by r0boto** [avast/android-styled-dialogs#124]
Hello, 

Material dialogs have a possibility to display icon in the header of the dialog. Are You planning to add this feature?

Something like this:
```
  SimpleDialogFragment
                .createBuilder(mCtx, mFragmentManager)
                .setMessage(text)
                .icon(R.drawable.icon)
                .show();

```

**Comment by destil** [comment]
Icons are not mentioned in Material Design Guidelines, so we don't plan to do it. You can create own dialog like IconDialogFragment and inherit from it, have a look at JayneDialogFragment from the demo app for inspiration.
