### ISSUE TITLE
Style contains key with bad entry

### ISSUE THREAD

**Issue by ernes87lp** [avast/android-styled-dialogs#25]
Everytime the dialog is shown, I get this errors. BTW, the dialog is shown correctly.

11-28 01:31:39.203: E/ResourceType(2540): Style contains key with bad entry: 0x010102dd
11-28 01:31:39.203: E/ResourceType(2540): Style contains key with bad entry: 0x0101035b
11-28 01:31:40.753: E/ResourceType(2540): Style contains key with bad entry: 0x010102dd

And so on...

Tested on API 8 and 9.

**Comment by kemicky** [comment]
@davidvavra :Thanks a million for this explanation.
 I was worried maybe I have some runtime error or bad code.

**Comment by davidvavra** [comment]
Blast from past :)
