### ISSUE TITLE
Regarding usage with API 14+ and FragmentManager

### ISSUE THREAD

**Issue by tmsbn** [avast/android-styled-dialogs#33]
I want to use this library with my application targeting API 14+. Hence I am only extending Activity in my activities, which gives access to only getFragmentManager()(not the support version) but the constructor requires the supportFragmentManager. How do i resolve this? I would like to avoid extending FragmentActivity if possible. Sorry If i missed something obvious here.

Excellent work on the library!!

**Comment by destil** [comment]
The new version 2.0.1 is based on Material design which requires appcompat-v7 (unless you are targetting Lollipop-only). We think that you will always need a support library (if you want to be up-to-date to Google's latest design language). I'm closing the issue.
