### ISSUE TITLE
Need to set DialogInterface.OnCancelListener on a ProgressDialogFragment

### ISSUE THREAD

**Issue by belandsoft** [avast/android-styled-dialogs#85]
As in title i need to add an OnCancelListener on a ProgressDialogFragment, what i want to do is something like this:

ProgressDialogFragment.createBuilder(this,
                    getSupportFragmentManager())
                    .setTitle(appContext.getString(R.string.progressDialogTitle))
                    .setMessage(appContext.getString(R.string.progressDialogMessage))
                    .setOnCancelListener(myOnCancelListener)
                    .show();
This will enable me to show a fragment from inside an asynktask and listen there for his cancellation.

**Comment by destil** [comment]
StyledDialogs have different architecture of listeners which survive rotation. You can listen to them in Activity or Fragment. 
ProgressDialog already has a support for OnCancelListener. Look into DemoActivity how it's used.
