### ISSUE TITLE
Add support for a dark theme

### ISSUE THREAD

**Issue by martinpelant** [avast/android-styled-dialogs#90]
Whenever app uses a dark theme some of the texts/controls are white but your dialogs still use white background so it's unreadable (white text on white background).
![device-2015-01-26-105252](https://cloud.githubusercontent.com/assets/398815/5897879/a4c84262-a549-11e4-83d0-e49dadce3e21.png)

**Comment by destil** [comment]
Yes dark theme would be great. But we won't probably add it unless we need it for some Avast app. It's a great opportunity for a pull request.
