### ISSUE TITLE
about dismiss

### ISSUE THREAD

**Issue by lijianyu** [avast/android-styled-dialogs#91]
how to use Butilder dismiss?

**Comment by destil** [comment]
I don't understand, can you explain in detail what you are trying to do?

**Comment by lijianyu** [comment]
I mean, if you can add dismiss() method in BaseDialogBuilder

**Comment by tomik-dev** [comment]
Hi, 
I don't see any reason for adding `dismiss()` to `BaseDialogBuilder`.
When you call `show()` method it returns a `DialogFragment` instance which has a `dismiss()` method.
