### ISSUE TITLE
Can ListDialogFragment be used inside a Fragment?

### ISSUE THREAD

**Issue by ayerkovich** [avast/android-styled-dialogs#93]
I'm able to display de ListDialogFragment inside a Fragment but it doesn't fire the onListItemSelected method when any item is selected.

I'm guessing not since:

        ListDialogFragment
                .createBuilder(getActivity(), getActivity().getSupportFragmentManager())
                ...
takes and activity as argument and not a fragment.

Any ideas?

**Comment by limojoe** [comment]
Did you use setTargetFragment?

**Comment by ayerkovich** [comment]
Thanks! That did the trick!
