### ISSUE TITLE
Can I add a button to a ProgressDialogFragment?

### ISSUE THREAD

**Issue by ayerkovich** [avast/android-styled-dialogs#94]
I need to provide the user with a way of cancelling a running task. How can I do that? Thanks.

**Comment by tomik-dev** [comment]
Hi,
styled dialogs can be greatly customized. You can see an example in the demo in `JayneHatDialogFragment`.
To create progress dialog with a button you can either use `SimpleDialogFragment` where you add a view containing progress bar in setView. Or better you can extend `ProgressDialogFragment` and adjust its `build(Builder)` method (take your inspiration from `SimpleDialogFragment`).
