### ISSUE TITLE
sdlDialogStyle attrs

### ISSUE THREAD

**Issue by gregriggins36** [avast/android-styled-dialogs#98]
Hi,

It seems like sdlDialogStyle is not defined anymore as an attribute. How would you customize for example the title color ?

Thanks.

**Comment by destil** [comment]
Hi,
according to [Material Design Specification](http://www.google.com/design/spec/components/dialogs.html), items like the title color should not be changed. Some items like the button color are set to `colorAccent`. Why do you need different title color?

**Comment by gregriggins36** [comment]
Hi,

I was just wondering what is the way now to customize the theme of the
Dialogs. If it's all taken from the colorAccent (colorPrimary and
colorPrimaryDark) that's fine.
Thanks.

**Comment by destil** [comment]
Yes it's taken from the main theme, no library-specific attributes.
